//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Proxies {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Proxies.IDo")]
    public interface IDo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDo/DoThis", ReplyAction="http://tempuri.org/IDo/DoThisResponse")]
        int DoThis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDo/DoThis", ReplyAction="http://tempuri.org/IDo/DoThisResponse")]
        System.Threading.Tasks.Task<int> DoThisAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDoChannel : Client.Proxies.IDo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoClient : System.ServiceModel.ClientBase<Client.Proxies.IDo>, Client.Proxies.IDo {
        
        public DoClient() {
        }
        
        public DoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DoThis() {
            return base.Channel.DoThis();
        }
        
        public System.Threading.Tasks.Task<int> DoThisAsync() {
            return base.Channel.DoThisAsync();
        }
    }
}
